### ISSUE TITLE
輔導癌症患者及家屬技巧

### ISSUE THREAD

**Issue by xycjscs** [xycjscs/KnowledgeBase-xiaoyibao#10]
### 作者

李慧芬 (香港癌症基金會港島癌協服務中心督導經理)

### 简介

患者情绪有八个阶段，如何疏解以及家属如何处理

### 网址

https://www.healthyhkec.org/download/2017-02-24/pisa_lee1.pdf

### 分类

PsychologicalDB

**Comment by TechQuery** [comment]
@xycjscs 要删掉标签重新添加才能触发 actions
