### ISSUE TITLE
PDF 转 Markdown 的可行性

### ISSUE THREAD

**Issue by TechQuery** [xycjscs/KnowledgeBase-xiaoyibao#3]
@xycjscs 我看 Read Me 上写了：

> 自动化 PDF 文档转 Markdown 文本

成熟工具我倒是找好了：

1. https://github.com/bsorrentino/pdf-tools
2. https://github.com/opengovsg/pdf2md

但是浏览了现有数据中所有 PDF 链接后，发现大多数文档制作非常精美，有很不规则的图文排版，很适合人类阅读，但不利于程序识别。

所以我的疑问是：做这个功能目的为何？因为现代 Web 浏览器内置 PDF 渲染能力，人类阅读已经非常舒服了，做文本转换是为了给 AI 训练吗？

**Comment by xycjscs** [comment]
是的 pdf转markdown是为了以RAG挂载在大语言模型，和为未来的大语言模型训练。
此项目针对群体较为复杂：
最终获益者为患者；仓库直接使用者为小胰宝或其他开源项目的技术人员；内容贡献者为医学相关专家。
面对此仓库，患者和医疗卫生人员可直接在渲染的网站上阅读pdf资料；小胰宝相关开发人员可快速构建RAG知识库测试LLM；其他开发人员可获取可用于预训练的预料和微调的QA对。

**Comment by TechQuery** [comment]
@xycjscs 我突然发现 [`downloader.py`][1] 就是用来批量下载 PDF 文件的吧？只不过它里面不带转换 Markdown 的功能。

[1]: https://github.com/xycjscs/KnowledgeBase-xiaoyibao/blob/main/tool%2Fdownloader.py

**Comment by xycjscs** [comment]
@TechQuery 是的，请帮忙确保两个工具可以分离独立工作，或者交互式选择功能。使用pdf和markdown的人群可能是不同的。

**Comment by TechQuery** [comment]
> 请帮忙确保两个工具可以分离独立工作，或者交互式选择功能。

你在本地安装 Node.js 及项目依赖，试用一下 [`fetch-PDF.sh`][1]，它可以一次性下载所有 PDF 并转换成 Markdown（所有文件都归类在不同各自的文件夹），核心总共两行命令，实在没必要分成两步。

[1]: https://github.com/xycjscs/KnowledgeBase-xiaoyibao/blob/main/tool%2Ffetch-PDF.sh

**Comment by xycjscs** [comment]
感谢👍 我会尽快试用并精简原有代码。在实践中我们发现大量资料以html形式存在于网络。下载器和转换器未来需要兼容不同格式的文件。不知道您能否帮忙？

**Comment by TechQuery** [comment]
> 感谢👍 我会尽快试用并精简原有代码。在实践中我们发现大量资料以html形式存在于网络。下载器和转换器未来需要兼容不同格式的文件。不知道您能否帮忙？

HTML 到 Markdown 的转换 JavaScript 工具库就更多了，再加上另一个 Python 上传脚本的逻辑，我其实可以写到一个 Node.js 脚本里，会比现在清晰得多。

**Comment by xycjscs** [comment]
👍👍👍这太棒了👏
